In [48]:
import ast
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from collections import Counter

In [49]:
df = pd.read_csv('/media/prince/5A4E832F4E83034D/Movie recomender/Train_v2/raw_movies_data.csv', low_memory=False)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [51]:
df['production_companies'].head()

0    [{"name": "Ingenious Film Partners", "id": 289...
1    [{"name": "Walt Disney Pictures", "id": 2}, {"...
2    [{"name": "Columbia Pictures", "id": 5}, {"nam...
3    [{"name": "Legendary Pictures", "id": 923}, {"...
4          [{"name": "Walt Disney Pictures", "id": 2}]
Name: production_companies, dtype: object

In [52]:
df['popularity'].min(), df['popularity'].max(), df['popularity'].mean()

(0.0, 875.581305, np.float64(21.492300588174057))

In [53]:
df.drop('homepage', axis=1 , inplace=True)

In [54]:
df['budget'].min(), df['budget'].max(), df['budget'].mean()

(0, 380000000, np.float64(29045039.87528628))

In [55]:
df[['keywords']].head()

                                            keywords
0  [{"id": 1463, "name": "culture clash"}, {"id":...
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...
4  [{"id": 818, "name": "based on novel"}, {"id":...

In [56]:
(df['budget'] == 0).value_counts()

budget
False    3766
True     1037
Name: count, dtype: int64

In [57]:
(df['revenue'] == 0).value_counts()

revenue
False    3376
True     1427
Name: count, dtype: int64

In [58]:
df['runtime'].unique()

array([162., 169., 148., 165., 132., 139., 100., 141., 153., 151., 154.,
       106., 149., 143., 150., 136., 144., 140., 161., 113., 187., 194.,
       147., 131., 124., 127., 130., 108., 104., 142., 125., 114., 103.,
       115., 137., 116., 122.,  93.,  98.,  91., 158.,  96., 109., 152.,
        94., 126., 112., 123., 135., 118.,  97., 119., 102., 120., 121.,
       166.,  99., 183., 175., 138., 157.,  92., 101., 111.,  89., 105.,
       107., 129.,  88.,  85., 163., 133.,  95.,  90., 110., 128., 156.,
       117., 146.,  82.,  78., 134., 170.,  76., 178.,  84., 155., 145.,
       180., 172., 167., 201., 179.,  83.,  87.,  80.,  74.,  81., 177.,
        86., 164., 159., 191., 189., 214.,   0.,  75., 192., 160., 219.,
       248., 188., 202., 173., 195.,  77.,  79.,  63., 229., 193., 254.,
        72.,  68., 199., 181., 242., 338.,  73., 216., 276.,  nan, 200.,
        69., 197., 184., 176., 185., 171., 174.,  46.,  53.,  42., 240.,
        41.,  67., 238., 186.,  70.,  14., 225., 207.,  66.,  59.,  25.,
        47.,  64.,  60.])

In [59]:
(df['runtime'] == 0).value_counts()

runtime
False    4768
True       35
Name: count, dtype: int64

In [60]:
(df['popularity'] == 0).value_counts()

popularity
False    4802
True        1
Name: count, dtype: int64

In [61]:
(df['vote_average'] == 0).value_counts()

vote_average
False    4740
True       63
Name: count, dtype: int64

In [62]:
(df['vote_count'] == 0).value_counts()

vote_count
False    4741
True       62
Name: count, dtype: int64

In [63]:
imputer_median = SimpleImputer(strategy="median")
imputer_mean = SimpleImputer(strategy="mean")

In [64]:
mean_columns = df[['runtime', 'vote_average']]
median_columns = df[['vote_count', 'popularity']]

In [65]:
df[['vote_count', 'popularity']] = df[['vote_count', 'popularity']].replace(0, np.nan) 
df[['runtime', 'vote_average']] = df[['runtime', 'vote_average']].replace(0, np.nan)

In [66]:
df[['vote_count', 'popularity']] = imputer_median.fit_transform(df[['vote_count', 'popularity']])
df[['runtime', 'vote_average']] = imputer_mean.fit_transform(df[['runtime', 'vote_average']])

In [67]:
df[['vote_count', 'popularity', 'runtime', 'vote_average']].describe()

         vote_count   popularity      runtime  vote_average
count   4803.000000  4803.000000  4803.000000   4803.000000
mean     693.341870    21.494992   107.660722      6.173143
std     1233.140496    31.815378    20.669331      0.966282
min        1.000000     0.000372    14.000000      0.500000
25%       59.000000     4.674558    94.000000      5.600000
50%      242.000000    12.924931   104.000000      6.200000
75%      737.000000    28.313505   117.500000      6.800000
max    13752.000000   875.581305   338.000000     10.000000

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   id                    4803 non-null   int64
 3   keywords              4803 non-null   object
 4   original_language     4803 non-null   object
 5   original_title        4803 non-null   object
 6   overview              4800 non-null   object
 7   popularity            4803 non-null   float64
 8   production_companies  4803 non-null   object
 9   production_countries  4803 non-null   object
 10  release_date          4802 non-null   object
 11  revenue               4803 non-null   int64
 12  runtime               4803 non-null   float64
 13  spoken_languages      4803 non-null   object
 14  status                4803 non-null   object
 15  tagline               3959 non-null   object
 16  title                 4803 non-null   object
 17  vote_average          4803 non-null   float64
 18  vote_count            4803 non-null   float64
dtypes: float64(4), int64(3), object(12)
memory usage: 713.1+ KB

In [69]:
df.drop(columns=['budget', 'revenue', 'original_title', 'production_countries', 'release_date', 'spoken_languages','status'], inplace=True)

In [70]:
df.drop(columns=['id'], inplace=True)

In [71]:
df.to_csv('clean_data.csv', index=False)

In [72]:
df['f_genres'] = df['genres'].apply(ast.literal_eval)

In [73]:
df['genre_names'] = df['f_genres'].apply(lambda x: [d['name'] for d in x])

In [74]:
df['genre_names']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genre_names, Length: 4803, dtype: object

In [75]:
df[['f_genres']]

                                               f_genres
0     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
3     [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
...                                                 ...
4798  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4799  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
4800  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4801                                                 []
4802                [{'id': 99, 'name': 'Documentary'}]

[4803 rows x 1 columns]

In [76]:
df['f_keywords'] = df['keywords'].apply(ast.literal_eval)

In [77]:
df['keywords_names'] = df['f_keywords'].apply(lambda x: [d['name'] for d in x])

In [78]:
df['keywords_names']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4798    [united states–mexico barrier, legs, arms, pap...
4799                                                   []
4800    [date, love at first sight, narration, investi...
4801                                                   []
4802            [obsession, camcorder, crush, dream girl]
Name: keywords_names, Length: 4803, dtype: object

In [79]:
df.to_csv('v3_cleaneed.csv')

In [80]:
from collections import Counter

# Flatten all keyword names directly (cleaned to lowercase and stripped)
all_keywords = [d['name'].strip().lower() for sub in df['f_keywords'] for d in sub if 'name' in d]

# Count keyword frequencies
keywords_counter = Counter(all_keywords)

# Get top 150 most common keywords
common_keywords = [item[0] for item in keywords_counter]

# Replace rare keywords with 'other'
cleaned = []
for row in df['keywords_names']:
    # ensure row is a list and cleaned
    new_list = []
    for key in row:
        k = key.strip().lower()  # clean it before comparing
        if k in common_keywords:
            new_list.append(k)
        
    new_list = list(set(new_list))
    cleaned.append(new_list)

# Update DataFrame
df['keywords_names'] = cleaned
len(keywords_counter)

IndexError: string index out of range

In [ ]:
from collections import Counter

# Flatten all keyword names directly (cleaned to lowercase and stripped)
all_keywords = [d['name'].strip().lower() for sub in df['f_keywords'] for d in sub if 'name' in d]

# Count keyword frequencies
keywords_counter = Counter(all_keywords)

# Get top 150 most common keywords
common_keywords = [item[0] for item in keywords_counter.most_common(200)]

# Replace rare keywords with 'other'
cleaned = []
for row in df['keywords_names']:
    # ensure row is a list and cleaned
    new_list = []
    for key in row:
        k = key.strip().lower()  # clean it before comparing
        if k in common_keywords:
            new_list.append(k)
        else:
            new_list.append('other')
    new_list = list(set(new_list))
    cleaned.append(new_list)

# Update DataFrame
df['keywords_names'] = cleaned
len(keywords_counter)

9811

In [ ]:
print(common_keywords[:10])
print(type(common_keywords[0]))

['woman director', 'independent film', 'duringcreditsstinger', 'based on novel', 'murder', 'aftercreditsstinger', 'violence', 'dystopia', 'sport', 'revenge']
<class 'str'>

In [ ]:
print(df['keywords_names'].iloc[0])
print(type(df['keywords_names'].iloc[0][0]))

['battle', 'space', 'romance', '3d', 'future', 'soldier', 'alien', 'other']
<class 'str'>

In [ ]:
sample_keywords = [k.strip().lower() for row in df['keywords_names'] for k in row]
matches = set(sample_keywords) & set(common_keywords)
print(len(matches), list(matches)[:20])

200 ["love of one's life", 'black people', 'space marine', 'wife husband relationship', 'detective', 'based on video game', 'cia', 'sport', 'gay', 'robot', 'based on young adult novel', 'romance', 'gangster', 'deception', 'soldier', 'corruption', 'killer', 'time travel', 'ship', 'writer']

In [ ]:
df['keywords_names'] = df['keywords_names'].apply(lambda x: ['other'] if not x else x)

In [ ]:
only_other_mask = df['keywords_names'].apply(lambda x: x == ['other'])
only_other_count = only_other_mask.sum()

In [ ]:
only_other_count

np.int64(1130)

In [ ]:
# df.to_csv('clean_data.csv', index=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   genres                4803 non-null   object
 1   keywords              4803 non-null   object
 2   original_language     4803 non-null   object
 3   overview              4800 non-null   object
 4   popularity            4803 non-null   float64
 5   production_companies  4803 non-null   object
 6   runtime               4803 non-null   float64
 7   tagline               3959 non-null   object
 8   title                 4803 non-null   object
 9   vote_average          4803 non-null   float64
 10  vote_count            4803 non-null   float64
 11  f_genres              4803 non-null   object
 12  genre_names           4803 non-null   object
 13  f_keywords            4803 non-null   object
 14  keywords_names        4803 non-null   object
dtypes: float64(4), object(11)
memory usage: 563.0+ KB